name: How to do Laravel Sail CI/CD

env:
  DB_CONNECTION: mysql
# In app .env this is set to mysql, but in GitHub Actions we need to set it to
# this value because the MySQL service is running on localhost. On our local app
# it runs in a Docker container named mysql, so we can use mysql as the host.
# But in GitHub Actions, we need to connect to the MySQL service using localhost and the exposed port.
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  DB_USERNAME: ${{ secrets.MYSQL_USER }}
  DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306

# This is a health check for the MySQL service
# mysqladmin → MySQL admin CLI tool
# ping → Check if the MySQL server is alive
# -p${MYSQL_PASSWORD} → Pass the password for authentication
        options: >-
          --health-cmd="mysqladmin ping -p$MYSQL_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
# This automatically caches npm dependencies based on the package-lock.json file. No need for actions/cache.
# Getting the npm packages from cache also happens here.
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Get Composer cache directory
        id: composer-cache
# prints the path of Composer’s cache directory. actions/cache will this way know where to cache the
# the Composer dependencies. This info will be now in the steps.composer-cache.outputs.dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
# Find the cached packages here, in this path
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}


# We must create a .env. However, the real .env is not committed to the repository.
# It is unavailable. So, we copy the .env.example to .env. The trick is the the workflow
# environment will override the values in .env, so we can set the database connection details
# in the workflow env and they will be used when running the tests.
      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

# Tell here the workflow to wait 5 s for the MySQL service to be fully ready before running the
# migrations and tests. This is a small buffer to ensure that the MySQL service is up and running
# before we try to connect to it.
      - name: Small DB readiness buffer
        run: sleep 5

# No need for seeding here, because we do not need seeding for the testing.
      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Fake Deploy
        run: echo "Laravel Sail app deployed"
